import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import "./custom.css"
import Providers from './providers'
import { Toaster } from "@/components/ui/toaster";


const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning className={roboto.className}>
      <body>
        <Providers>
          <Toaster />
          {children}
        </Providers>
      </body>
    </html>
  );
}
